---
- name: "Kill hwlatdetect if some was left runinng"
  ansible.builtin.command: killall hwlatdetect
  register: killall_hwlatdetect_cmd
  failed_when: "killall_hwlatdetect_cmd.rc != 0 and 'hwlatdetect: no process found' not in killall_hwlatdetect_cmd.stderr"
  changed_when: "killall_hwlatdetect_cmd.rc == 0"

- name: "Start hwlatdetect"
  ansible.builtin.shell: |
    nohup hwlatdetect \
      --duration "{{ hwlatdetect_helper_test_duration }}" \
      --threshold "{{ hwlatdetect_helper_test_threshold }}" \
      --window "{{ hwlatdetect_helper_test_window }}" \
      --width "{{ hwlatdetect_helper_test_width }}" \
      &>/root/ansible-role-hwlatdetect_helper.log &
    echo $! >/root/ansible-role-hwlatdetect_helper.pid
...
